### ISSUE TITLE
Recent builds are failing; dependencies need updating

### ISSUE THREAD

**Issue by drhuffman12** [ilanusse/praetorian#3]
Travis has been updated to use Crystal 0.29.0.

The recent builds (e.g.: https://travis-ci.org/ilanusse/praetorian/builds/544851510) use Ameba 0.9.0, and attempt to build using Crystal 0.29.0, which causes Ameba to error.

Ameba has been updated to 0.10.0 for Crystal 0.29.0 compatibility.

**Comment by drhuffman12** [comment]
@ilanusse, please review.

**Comment by ilanusse** [comment]
Sorry, was on vacation. Done!
